name: CMake

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    name: ${{matrix.name}}
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            name: Linux
            cache-key: linux
            release-suffix: LIN64
            cmake-args: -D32BLIT_PATH=$GITHUB_WORKSPACE/32blit
            apt-packages: libsdl2-dev libsdl2-image-dev python3-setuptools

    runs-on: ${{matrix.os}}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: main

    - name: Checkout 32Blit API
      uses: actions/checkout@v2
      with:
        repository: pimoroni/32blit-beta
        path: 32blit
      
    # Linux deps
    - name: Install deps
      if: runner.os == 'Linux'
      run: |
        sudo apt update && sudo apt install ${{matrix.apt-packages}}
        pip3 install 32blit
        
    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/main/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/main/build
      run: cmake $GITHUB_WORKSPACE/main -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_INSTALL_PREFIX=`pwd` ${{matrix.cmake-args}}

    - name: Build
      working-directory: ${{runner.workspace}}/main/build
      shell: bash
      run: |
        cmake --build . --config $BUILD_TYPE -j 2
